In [1]:
#ARRAY 10 ELEMENTOS

import numpy as np

array = np.arange(10)

array[5:9] = 0

print(array)

[0 1 2 3 4 0 0 0 0 9]


In [2]:
import numpy as np

array = np.array([[1, 2],
                  [3, 4],
                  [5, 6]])


print("Shape:", array.shape)

print("2ª linha:", array[1])

Shape: (3, 2)
2ª linha: [3 4]


In [3]:
import numpy as np

array = np.array([[1, 2],
                  [3, 4],
                  [5, 6]])

print("2ª coluna:", array[:, 1])

2ª coluna: [2 4 6]


In [4]:
import numpy as np

array = np.array([[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 10],
                  [11, 12, 13, 14, 15],
                  [16, 17, 18, 19, 20]])

print("3ª linha:", array[2])

3ª linha: [11 12 13 14 15]


In [5]:
import numpy as np

array = np.array([[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 10],
                  [11, 12, 13, 14, 15],
                  [16, 17, 18, 19, 20]])

resultado = array[0:2, 1:3]

print(resultado)

[[2 3]
 [7 8]]


In [6]:
import numpy as np

array = np.array([[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 10],
                  [11, 12, 13, 14, 15],
                  [16, 17, 18, 19, 20]])

print(array[1:3, 0:3])

[[ 6  7  8]
 [11 12 13]]
